<?php defined('ABSPATH') OR die('No direct access.');
/*
Plugin Name: Email Encoder Bundle
Plugin URI: http://www.freelancephp.net/email-encoder-php-class-wp-plugin/
Description: Protect email addresses on your site and hide them from spambots by using an encoding method. Easy to use, flexible .
Author: Victor Villaverde Laan
Version: 1.0.0
Author URI: http://www.freelancephp.net
License: Dual licensed under the MIT and GPL licenses
*/

// plugin file
if (!defined('EMAIL_ENCODER_BUNDLE_FILE')) {
    define('EMAIL_ENCODER_BUNDLE_FILE', __FILE__);
}

// plugin version
if (!defined('EMAIL_ENCODER_BUNDLE_VERSION')) {
    define('EMAIL_ENCODER_BUNDLE_VERSION', '1.0.0');
}

// plugin key
if (!defined('EMAIL_ENCODER_BUNDLE_KEY')) {
    define('EMAIL_ENCODER_BUNDLE_KEY', 'WP_Email_Encoder_Bundle');
}

// plugin domain for translation
if (!defined('EMAIL_ENCODER_BUNDLE_DOMAIN')) {
    define('EMAIL_ENCODER_BUNDLE_DOMAIN', 'email-encoder-bundle');
}

// check plugin compatibility
if (isset($wp_version)
            AND version_compare(preg_replace('/-.*$/', '', $wp_version), '3.4', '>=')
            AND version_compare(phpversion(), '5.3.13', '>=')) {

    // include classes
    require_once('includes/class-eeb-admin.php');
    require_once('includes/class-eeb-site.php');
    require_once('includes/template-functions.php');

    // for testing purposes
    if (file_exists(dirname(__FILE__) . '/../../wp-plugin-tester/tests/test-email-encoder-bundle.php')) {
        require_once('/../../wp-plugin-tester/wp-plugin-tester.php');
        require_once('/../../wp-plugin-tester/tests/test-email-encoder-bundle.php');
    }

    // create instance
    $EebSite = new EebSite;

    // handle AJAX request
    if (!empty($_GET['ajaxEncodeEmail'])):
        // input vars
        $method = $_GET['method'];
        $email = $_GET['email'];
        $display = (empty($_GET['display'])) ? $email : $_GET['display'];

        echo $EebSite->encode_email($email, $display, '', $method, TRUE);
        exit;
    endif;

} else {

    // set error message
    if (function_exists('eeb_error_notice')):
        function eeb_error_notice() {
            echo '<div class="error">'
                . __('<p>Warning - The plugin <strong>Email Encoder Bundle</strong> requires PHP 5.4+ and WP 3.4+.'
                        . ' Please upgrade your PHP and/or WordPress. '
                        . '<br/>Disable the plugin to remove this message.</p>', EMAIL_ENCODER_BUNDLE_DOMAIN)
                . '</div>';
        }

        add_action('admin_notices', 'eeb_error_notice');
    endif;

}

/* ommit PHP closing tag, to prevent unwanted whitespace at the end of the parts generated by the included files */