<?php
if ( ! function_exists( 'lim_email_html_encode' ) ):

// Info (optional)
$lim_email_html_encode = array(
	'name' => 'Html Encode',
	'description' => 'Email encode method using antispambot() built-in WordPress (<a href="http://codex.wordpress.org/Function_Reference/antispambot" target="_blank">more info</a>).',
);

/**
 * lim_email_html_encode()
 * Default email encode method converting email to html entities
 * 
 * @package WP_Email_Encoder_Bundle
 * @param string $email  the email to encode
 * @param string $display  the display showing on the page
 * @param string $obj  WP_Email_Encoder_Bundle object
 * @return string
 */
function lim_email_html_encode( $email, $display, $obj ) {
	$email = $obj->get_htmlent( $email );
	$display = $obj->get_htmlent( $display );

	// return encode mailto link
	return '<a class="'. $obj->options[ 'class_name' ] .'" href="mailto:' . $email . '">' . $display . '</a>';
}

endif;

/*?> // ommit closing tag, to prevent unwanted whitespace at the end of the parts generated by the included files */