<?php defined('ABSPATH') OR die('No direct access.');

/**
 * Deprecated template Functions
 *
 * @package Email_Encoder_Bundle
 * @category WordPress Plugins
 */

/**
 * Template function for encoding email
 *
 * @deprecated
 *
 * @global EebSite $EebSite
 * @param string $email
 * @param string $display  if non given will be same as email
 * @param string $method Optional, else the default setted method will; be used
 * @param string $extra_attrs  Optional
 * @return string
 */
if (!function_exists('encode_email')):
    function encode_email($email, $display = NULL, $method = NULL, $extra_attrs = '') {
        return eeb_email($email, $display, $extra_attrs, $method);
    }
endif;

/**
 * Template function for encoding content
 *
 * @deprecated
 *
 * @global EebSite $EebSite
 * @param string $content
 * @param string $method Optional, default NULL
 * @return string
 */
if (!function_exists('encode_content')):
    function encode_content($content, $method = NULL) {
        return eeb_content($content, $method);
    }
endif;

/**
 * Template function for encoding emails in the given content
 *
 * @deprecated
 *
 * @global EebSite $EebSite
 * @param string $content
 * @param boolean $enc_tags Optional, default TRUE
 * @param boolean $enc_mailtos  Optional, default TRUE
 * @param boolean $enc_plain_emails Optional, default TRUE
 * @return string
 */
if (!function_exists('encode_email_filter')):
    function encode_email_filter($content, $enc_tags = TRUE, $enc_mailtos = TRUE, $enc_plain_emails = TRUE) {
        return eeb_email_filter($content, $enc_tags, $enc_mailtos, $enc_plain_emails);
    }
endif;

/* ommit PHP closing tag, to prevent unwanted whitespace at the end of the parts generated by the included files */